### ISSUE TITLE
uploadFile 응답이 없는 경우

### ISSUE THREAD

**Issue by potados99** [inu-appcenter/shareU_Server#2]
## 배경

[안드로이드 측 이슈](https://github.com/inu-appcenter/Share_U_Android/issues/15) 처리하다가 발견했습니다.

## 문제

[이 곳](https://github.com/inu-appcenter/shareU_Server/blob/2d5acb7a5700efa0b4a321bc3ae7d1614e20eae2/routes/document/upload.js#L42)의 `uploadfile` 라우팅 구현을 보면, **return이 없는 경우**가 존재합니다. 

때문에 클라이언트의 요청이 timeout에 빠지는 경우가 존재합니다.

모든 경우에서 (요청이 Bad request일 지라도) 응답을 전달하도록 해주세요..!

**Comment by ryuspace** [comment]
들었냐 박쏘현!!!!

**Comment by sohyeonpark0901** [comment]
확인.
